FROM php:7.0.24-apache
COPY ./src /var/www/html/

WORKDIR /var/www/html/

RUN \
chmod -R 777 /var/www/html/files \
&& ln -s /home/site/wwwroot/files /var/www/html/files

# Configure ports
EXPOSE 2222 80

# Run apt-get, to install the SSH server
RUN apt-get update \ 
    && apt-get install -y --no-install-recommends openssh-server \
    && echo "root:Docker!" | chpasswd

#Copy the sshd_config file to its new location
COPY sshd_config /etc/ssh/

# Start the SSH service
RUN service ssh start

# Copy init_container.sh to the /bin directory
COPY init_container.sh /bin/

# Run the chmod command to change permissions on above file in the /bin directory
RUN chmod 755 /bin/init_container.sh 

# run commands in init_container.sh
CMD ["/bin/init_container.sh"]

# Ref: https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image
